struct MetroLineTopology {
    static let M1: [[String]] = [
        ["RHO FIERAMILANO", "AMENDOLA", "BUONARROTI", "PAGANO", "CONCILIAZIONE", "CADORNA FN M1", "CAIROLI", "CORDUSIO", "DUOMO M1", "SAN BABILA", "PALESTRO", "PERO", "P.TA VENEZIA", "LIMA", "LORETO M1", "PASTEUR", "ROVERETO", "TURRO", "GORLA", "PRECOTTO", "VILLA S.G.", "SESTO MARELLI", "MOLINO DORINO", "SESTO RONDO", "SESTO 1 MAGGIO FS", "S.LEONARDO", "BONOLA", "URUGUAY", "LAMPUGNANO", "QT8", "LOTTO FIERAMILANOCITY"],
        ["SESTO 1 MAGGIO FS", "LORETO M1", "LIMA", "P.TA VENEZIA", "PALESTRO", "SAN BABILA", "DUOMO M1", "CORDUSIO", "CAIROLI", "CADORNA FN M1", "CONCILIAZIONE", "SESTO RONDO", "PAGANO", "BUONARROTI", "AMENDOLA", "LOTTO FIERAMILANOCITY", "QT8", "LAMPUGNANO", "URUGUAY", "BONOLA", "S.LEONARDO", "MOLINO DORINO", "SESTO MARELLI", "PERO", "RHO FIERAMILANO", "VILLA S.G.", "PRECOTTO", "GORLA", "TURRO", "ROVERETO", "PASTEUR"],
    ]
    static let M2: [[String]] = [
        ["ASSAGO MILANOFIORI FORUM", "MOSCOVA", "GARIBALDI FS", "GIOIA", "CENTRALE FS", "CAIAZZO", "LORETO M2", "PIOLA", "LAMBRATE FS", "UDINE", "CIMIANO", "ASSAGO MILANOFIORI NORD", "CRESCENZAGO", "CASCINA GOBBA", "VIMODRONE", "CASCINA BURRONA", "CERNUSCO SUL NAVIGLIO", "VILLA FIORITA", "CASSINA DE PECCHI", "BUSSERO", "VILLA POMPEA", "GORGONZOLA", "FAMAGOSTA", "CASCINA ANTONIETTA", "GESSATE", "ROMOLO", "P.TA GENOVA F.S.", "S.AGOSTINO", "S.AMBROGIO", "CADORNA FN M2", "LANZA"],
        ["GESSATE", "VIMODRONE", "CASCINA GOBBA", "CRESCENZAGO", "CIMIANO", "UDINE", "LAMBRATE FS", "PIOLA", "LORETO M2", "CAIAZZO", "CENTRALE FS", "CASCINA ANTONIETTA", "GIOIA", "GARIBALDI FS", "MOSCOVA", "LANZA", "CADORNA FN M2", "S.AMBROGIO", "S.AGOSTINO", "P.TA GENOVA F.S.", "ROMOLO", "FAMAGOSTA", "GORGONZOLA", "ASSAGO MILANOFIORI NORD", "ASSAGO MILANOFIORI FORUM", "VILLA POMPEA", "BUSSERO", "CASSINA DE PECCHI", "VILLA FIORITA", "CERNUSCO SUL NAVIGLIO", "CASCINA BURRONA"],
    ]
    static let M3: [[String]] = [
        ["COMASINA", "TURATI", "MONTENAPOLEONE", "DUOMO M3", "MISSORI", "CROCETTA", "PORTA ROMANA", "LODI T.I.B.B.", "BRENTA", "CORVETTO", "PORTO DI MARE", "AFFORI FN", "ROGOREDO FS", "SAN DONATO", "AFFORI CENTRO", "DERGANO", "MACIACHINI", "ZARA", "SONDRIO", "CENTRALE FS", "REPUBBLICA"],
        ["SAN DONATO", "DUOMO M3", "MONTENAPOLEONE", "TURATI", "REPUBBLICA", "CENTRALE FS", "SONDRIO", "ZARA", "MACIACHINI", "DERGANO", "AFFORI CENTRO", "ROGOREDO FS", "AFFORI FN", "COMASINA", "PORTO DI MARE", "CORVETTO", "BRENTA", "LODI T.I.B.B.", "PORTA ROMANA", "CROCETTA", "MISSORI"],
    ]
    static let M4: [[String]] = [
        ["LINATE AEROPORTO", "SANTA SOFIA", "VETRA", "DE AMICIS", "SAN AMBROGIO", "CONI ZUGNA", "CALIFORNIA", "BOLIVAR", "TOLSTOJ", "FRATTINI", "GELSOMINI", "REPETTI", "SEGNERI", "SAN CRISTOFORO", "STAZIONE FORLANINI", "ARGONNE", "SUSA", "DATEO", "TRICOLORE", "SAN BABILA", "SFORZA-POLICLINICO"],
        ["SAN CRISTOFORO", "DE AMICIS", "VETRA", "SANTA SOFIA", "SFORZA-POLICLINICO", "SAN BABILA", "TRICOLORE", "DATEO", "SUSA", "ARGONNE", "STAZIONE FORLANINI", "SEGNERI", "REPETTI", "LINATE AEROPORTO", "GELSOMINI", "FRATTINI", "TOLSTOJ", "BOLIVAR", "CALIFORNIA", "CONI ZUGNA", "SAN AMBROGIO"],
    ]
    static let M5: [[String]] = [
        ["BIGNAMI", "MONUMENTALE", "CENISIO", "GERUSALEMME", "DOMODOSSOLA", "TRE TORRI", "PORTELLO", "LOTTO M5", "SEGESTA", "SAN SIRO IPPODROMO", "SAN SIRO STADIO", "PONALE", "BICOCCA", "CA GRANDA", "ISTRIA", "MARCHE", "ZARA", "ISOLA", "GARIBALDI FS"],
        ["SAN SIRO STADIO", "MONUMENTALE", "GARIBALDI FS", "ISOLA", "ZARA", "MARCHE", "ISTRIA", "CA GRANDA", "BICOCCA", "PONALE", "BIGNAMI", "SAN SIRO IPPODROMO", "SEGESTA", "LOTTO M5", "PORTELLO", "TRE TORRI", "DOMODOSSOLA", "GERUSALEMME", "CENISIO"],
    ]
}
